package types

type MessageId = int32
type Message struct {
	MessageID                    int32                          `json:"message_id,omitempty"`
	MessageThreadId              int32                          `json:"message_thread_id,omitempty"`
	From                         *User                          `json:"from,omitempty"`
	SenderChat                   *Chat                          `json:"sender_chat,omitempty"`
	Date                         int32                          `json:"date"`
	Chat                         *Chat                          `json:"chat,omitempty"`
	ForwardFrom                  *User                          `json:"forward_from,omitempty"`
	ForwardFromChat              *Chat                          `json:"forward_from_chat,omitempty"`
	ForwardFromMessageId         int32                          `json:"forward_from_message_id,omitempty"`
	ForwardSignature             string                         `json:"forward_signature,omitempty"`
	ForwardSenderName            string                         `json:"forward_sender_name,omitempty"`
	ForwardDate                  int32                          `json:"forward_date,omitempty"`
	IsTopicMessage               bool                           `json:"is_topic_message,omitempty"`
	IsAutomaticForward           bool                           `json:"is_automatic_forward,omitempty"`
	ReplyToMessage               *Message                       `json:"reply_to_message,omitempty"`
	ViaBot                       *User                          `json:"via_bot,omitempty"`
	EditDate                     int32                          `json:"edit_date,omitempty"`
	HasProtectedContent          bool                           `json:"has_protected_content,omitempty"`
	MediaGroupId                 string                         `json:"media_group_id,omitempty"`
	AuthorSignature              string                         `json:"author_signature,omitempty"`
	Text                         string                         `json:"text,omitempty"`
	Entities                     []*MessageEntity               `json:"entities,omitempty"`
	Animation                    *TelegramAnimation             `json:"animation,omitempty"`
	Audio                        *Audio                         `json:"audio,omitempty"`
	Document                     *Document                      `json:"document,omitempty"`
	Photo                        []*PhotoSize                   `json:"photo,omitempty"`
	Sticker                      *TelegramSticker               `json:"sticker,omitempty"`
	Video                        *Video                         `json:"video,omitempty"`
	VideoNote                    *VideoNote                     `json:"video_note,omitempty"`
	Voice                        *Voice                         `json:"voice,omitempty"`
	Caption                      string                         `json:"caption,omitempty"`
	CaptionEntities              []MessageEntity                `json:"caption_entities,omitempty"`
	Contact                      *Contact                       `json:"contact,omitempty"`
	Dice                         *Dice                          `json:"dice,omitempty"`
	Game                         *TelegramGame                  `json:"game,omitempty"`
	Poll                         *Poll                          `json:"poll,omitempty"`
	Venue                        *Venue                         `json:"venue,omitempty"`
	Location                     *Location                      `json:"location,omitempty"`
	NewChatMember                *[]User                        `json:"new_chat_members,omitempty"`
	LeftChatMember               *User                          `json:"left_chat_member,omitempty"`
	NewChatTitle                 string                         `json:"new_chat_title,omitempty"`
	NewChatPhoto                 []PhotoSize                    `json:"new_chat_photo,omitempty"`
	DeletChatPhoto               bool                           `json:"delete_chat_photo,omitempty"`
	GroupChatCreated             bool                           `json:"group_chat_created,omitempty"`
	SuperGroupChatCreated        bool                           `json:"supergroup_chat_created,omitempty"`
	ChannelChatCreated           bool                           `json:"channel_chat_created,omitempty"`
	MsgAutoDeletTimerChanged     *MessageAutoDeleteTimerChanged `json:"message_auto_delete_timer_changed,omitempty"`
	MigrateToChatId              int32                          `json:"migrate_to_chat_id,omitempty"`
	MigrateFromChatId            int32                          `json:"migrate_from_chat_id,omitempty"`
	PinnedMessage                *Message                       `json:"pinned_message,omitempty"`
	Invoice                      *TelegramInvoice               `json:"invoice,omitempty"`
	SuccessfulPayment            *TelegramSuccessfulPayment     `json:"successful_payment,omitempty"`
	ConnectedWebsite             string                         `json:"connected_website,omitempty"`
	PassportData                 *TelegramPassportData          `json:"passport_data,omitempty"`
	ProximityAlertTrigered       *ProximityAlertTrigered        `json:"proximity_alert_triggered,omitempty"`
	ForumTopicCreated            *ForumTopicCreated             `json:"forum_topic_created,omitempty"`
	ForumTopicClosed             *ForumTopicClosed              `json:"forum_topic_closed,omitempty"`
	ForumTopicReopened           *ForumTopicReopened            `json:"forum_topic_reopened,omitempty"`
	VideoChatSheduled            *VideoChatScheduled            `json:"video_chat_scheduled,omitempty"`
	VideoChatStarted             *VideoChatStarted              `json:"video_chat_started,omitempty"`
	VideoChatEnded               *VideoChatEnded                `json:"video_chat_ended,omitempty"`
	VideoChatParticipantsInvited *VideoChatParticipantsInvited  `json:"video_chat_participants_invited,omitempty"`
	WebAppData                   *WebAppData                    `json:"web_app_data"`
	ReplyMarkup                  *InlineKeyboardMarkup          `json:"reply_markup,omitempty"`
}
